Added check to see if database exists and is ready

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -91,13 +91,19 @@ jobs:
         done
         echo "SQL Server is available!"
 
-    # - name: Check SQL Server connection with sqlcmd
-    #   run: |
-    #     docker run --rm --network host mcr.microsoft.com/mssql-tools \
-    #       /bin/bash -c "/opt/mssql-tools/bin/sqlcmd -S localhost,11433 -U sa -P \"$DB_PASSWORD\" -Q \"SELECT name FROM sys.databases WHERE name = 'ManufacturerManagerWithMudBlazor';\""
-    #   env:
-    #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
-    #   continue-on-error: false
+    - name: Fail if DB missing
+      env:
+        SA_PASSWORD: ${{ secrets.SA_PASSWORD }}
+      run: |
+        RESULT=$(docker exec db /opt/mssql-tools/bin/sqlcmd \
+          -S localhost -U sa -P "$SA_PASSWORD" \
+          -Q "SELECT COUNT(*) FROM sys.databases WHERE name = 'ManufacturerManagerWithMudBlazor';" | tail -n 1)
+        if [ "$RESULT" -ne 1 ]; then
+          echo "Database not found!"
+          exit 1
+        else
+          echo "Database exists and ready."
+        fi
     
     - name: Start MMUserInterface in background
       shell: bash
