Remove health checks for testing purposes

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -70,21 +70,21 @@ jobs:
           -p 11433:1433 \
           jaburrow/manufacturermanagerseeded:latest
 
-    - name: Wait for SQL Server to be ready
-      shell: bash
-      env:
-        SA_PASSWORD: ${{ secrets.DB_PASSWORD }}
-      run: |
-        for i in {1..60}; do
-          if docker exec seeded-db /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$SA_PASSWORD" -Q "SELECT 1" &> /dev/null; then
-            echo "SQL Server is ready!"
-            exit 0
-          fi
-          echo "Waiting for SQL Server...{i}"
-          sleep 2
-        done
-        echo "SQL Server did not become ready in time."
-        exit 1
+    # - name: Wait for SQL Server to be ready
+    #   shell: bash
+    #   env:
+    #     SA_PASSWORD: ${{ secrets.DB_PASSWORD }}
+    #   run: |
+    #     for i in {1..60}; do
+    #       if docker exec seeded-db /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$SA_PASSWORD" -Q "SELECT 1" &> /dev/null; then
+    #         echo "SQL Server is ready!"
+    #         exit 0
+    #       fi
+    #       echo "Waiting for SQL Server...{{i}}"
+    #       sleep 2
+    #     done
+    #     echo "SQL Server did not become ready in time."
+    #     exit 1
     
     - name: Start MMUserInterface in background
       shell: bash
@@ -93,19 +93,19 @@ jobs:
         sleep 20
       working-directory: MMUserInterface
 
-    - name: Check if MMUserInterface is up
-      shell: bash
-      run: |
-        for i in {1..0}; do
-          if curl -k --silent --fail https://127.0.0.1:5245/; then
-            echo "MMUserInterface is up!"
-            exit 0
-          fi
-          echo "Waiting for MMUserInterface..."
-          sleep 2
-        done
-        echo "MMUserInterface did not become ready in time."
-        exit 1
+    # - name: Check if MMUserInterface is up
+    #   shell: bash
+    #   run: |
+    #     for i in {1..0}; do
+    #       if curl -k --silent --fail https://127.0.0.1:5245/; then
+    #         echo "MMUserInterface is up!"
+    #         exit 0
+    #       fi
+    #       echo "Waiting for MMUserInterface..."
+    #       sleep 2
+    #     done
+    #     echo "MMUserInterface did not become ready in time."
+    #     exit 1
 
     - name: Run Playwright tests over HTTPS
       shell: pwsh
